config/routes.rb
Rails.application.routes.draw do
	root 'static#home'
  get '/home', to: 'static#home' 
  get '/lessons', to: 'static#lessons'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  get '/quiz', to: 'static#quiz'
  get '/equine_first_aid_courses', to: 'static#equine_first_aid_courses'
  get '/success_stories', to: 'static#success_stories'
  get '/free_resources', to: 'static#free_resources'
  get '/faq', to: 'static#faq'
  get '/horse-anatomy', to: 'static#horse_anatomy'
  get '/online-first-aid', to: 'static#online_first_aid'
  get '/course-walks', to: 'static#course_walks'

  post '/newsletter-sign-up', to: 'static#newsletter_sign_up'
  post '/newsletter-sign-up', to: 'posts#newsletter_sign_up'
  post '/newsletter-sign-up', to: 'application#newsletter_sign_up'


  #blog
  get '/blog', to: 'posts#index'
  get '/blog/admin', to: 'posts#admin'
  resources :posts, path: 'blog'
  get 'drafts', to: 'posts#draft_index'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter_subscriber.rb
class NewsletterSubscriber < ApplicationRecord
	before_save :downcase_email
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
						format: { with: VALID_EMAIL_REGEX},
						uniqueness: { case_sensitive: false }

	private
  
  def downcase_email
    self.email = email.downcase
  end
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :content, presence: true
	mount_uploader :image, ImageUploader

	extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
   slug.blank? || title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def newsletter_sign_up
    @newsletter_subscriber = NewsletterSubscriber.new(newsletter_subscriber_params)
    if @newsletter_subscriber.save
      flash[:success] = "Thanks for signing up - we'll be in touch soon with the latest from NKC Equestrian Training!"
      redirect_to root_url
    else
      flash[:error] = "Sorry, please make sure you submit a valid name and email address"
      redirect_to root_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate, only: [:admin, :new, :create, :edit, :update, :destroy, :draft_index]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
  	@posts = Post.all.where.not(draft: true).order("created_at DESC")
	end

	def draft_index
  	@posts = Post.all.where(draft: true).order("created_at DESC")
	end

	def show
		if request.path != post_path(@post)
			redirect_to @post, status: :moved_permanently
		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
	  if @post.save
	  	flash[:success] = "The post was created!"
	   	redirect_to @post
	  else 
	  	render ‘new’
	  end 
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = 'The post was updated!'
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		flash[:success] = 'The post was deleted'
		redirect_to root_path
	end

	def admin
		redirect_to blog_url if authenticate
	end

protected
	def authenticate
    authenticate_or_request_with_http_basic do |username, password|
   		admin_username = Rails.application.secrets.admin_username
   		admin_password = Rails.application.secrets.admin_password
   		session[:admin] = true if (username == admin_username && password == admin_password)
  	end
  end

private

	def post_params
		params.require(:post).permit(:title, :content, :image, :slug, :draft)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def lessons
  end

  def contact
  end

  def about
  end

  def quiz
  end

  private

  def newsletter_subscriber_params
    params.require(:newsletter_subscriber).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_bio.html.erb
<p>I gained my BHSAI qualification in 2005, and I have combined teaching as a freelance instructor alongside managing equestrian centres both in the UK and in Greece.</p>

<h3>Career Highlights:</h3>
<ul>
	<li>Winner of the Hendelah Waley Equestrian Fund in 2006. A bursary set up for young instructors to develop their career</li>
	<li>Regional Finalist BHS Young Instructor of the Year 2007, an invaluable day of coaching and development where I gained some very positive and encouraging feedback on my teaching.</li>
	<li>Awarded an MSc in Applied Equine Science with distinction in 2010.</li>
	<li>showing my lovely horse Castleview Othello at County level (2011, 2012, 2013)</li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="navbar">
	
	<nav>
		<%= link_to image_tag("NKC_logo_white.png", alt: "NKC Equestrian Training", class: "logo-footer"), root_path %>
		<ul class = "nav navbar-nav navbar-right">
			<li><a href="https://bookwhen.com/nkcequestriantraining" target="_blank" class="btn btn-info">Book online</a></li>
			<li><a href="https://www.facebook.com/nkcequestriantraining/" target="_blank">Follow on Facebook</a></li>
		</ul>

	</nav>

	</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<%= link_to image_tag("NKC_logo_black.png", alt: "NKC Equestrian", class: "logo-header"), root_path %>	
			<span id="menu-icon" class = "icon-bar"></span>
			<ul class = "nav navbar-nav navbar-right">
				<% if session[:admin] then %>
					<li><%= link_to 'New Post[Admin]', new_post_path %></li>
					<li><%= link_to 'Drafts [Admin]', drafts_path %></li>
					<li><%= link_to "Blog", posts_url %>
				<% else %>
					<li><%= link_to "Horse First Aid", equine_first_aid_courses_path %></li>
					<li><%= link_to "Horse Anatomy", horse_anatomy_path %></li>
					<li><%= link_to "Online First Aid", online_first_aid_path %></li>
					<li><%= link_to "Blog", posts_url %>
					<li><%= link_to "Contact Us", contact_path %></li>
					<li><%= link_to "FAQ", faq_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render '/google_analytics' %>
    <title>NKC Equestrian Training</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    	<%= yield %>
      <%= render 'shared/newslettersign_up' %>
    	<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<%= render "shared/error_messages" %>
	<%= f.label :title %><br>
	<%= f.text_field :title, placeholder: "Type the blog title here" %><br>

	<%= f.label :content %><br>
	<%= f.text_area :content, size: "60x12", placeholder: "Type the blog content here" %><br>

	<%= f.label :image%><br>
	<%= f.file_field :image%><br>

	<%= f.label :draft, value: "Draft?" %>
	<%= f.check_box :draft, checked: "checked" %><br><br>
	
	<%= f.submit %>
<% end %>

app/views/posts/_index_body.html.erb
<% @posts.each do |post| %>
	<%= link_to(image_tag(post.image_url.to_s, class: "homepage-course"), post) %>
	<% if session[:admin] then %>
 		<%= link_to edit_post_path(post), class: "btn btn-default" do %>
 			<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
 		<% end %>
	<% end %>
<% end %>

app/views/posts/draft_index.html.erb
<% provide(:title, 'Drafts') %>
<%= render 'index_body' %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
	<%= render 'index_body' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<h1><%= @post.title %></h1>
<%= image_tag @post.image_url.to_s, class: "img-responsive blog-image" %>
<p><%= @post.content.html_safe %></p>

<% if session[:admin] then %>
 <%= link_to edit_post_path(@post), class: "btn btn-default" do %>
   <span class="glyphicon glyphicon-align-left" aria-hidden="true">
   </span> Edit
 <% end %>
 <%= link_to @post, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" do %>
   <span class="glyphicon glyphicon-trash" aria-hidden="true">
   </span> Delete
 <% end %> 
<% end %>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
 <div>
 	<p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
  <ul>
	  <% @post.errors.full_messages.each do |msg| %>
	  	<li><%= msg %></li>
	  <% end %>
  </ul> 
 </div>
<% end %>

app/views/shared/_newslettersign_up.html.erb
</br>
<div class='newsletter-form'>
<% @newsletter_subscriber = NewsletterSubscriber.new %>
	<h3>Want to get the latest updates from NKC Equestrain Training?</br>
	Sign up to the newsletter below</h3>
	<%= form_for @newsletter_subscriber, url: {action: "newsletter_sign_up"} do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.submit "Subscribe", class: "btn btn-success" %>
	<% end %>
</div>